
runtime: python39

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
