runtime: python39

# Basic scaling for cost efficiency
basic_scaling:
  max_instances: 2
  idle_timeout: 10m

# Environment variables
env_variables:
  FLASK_ENV: production

# Resource settings
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# File upload settings
handlers:
- url: /static
  static_dir: static
  secure: optional

- url: /.*
  script: auto
  secure: optional

# Skip certain files during deployment
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?downloads/.*$
- ^(.*/)?static/clips/.*$
- node_modules/
- .git/