
runtime: python
env: flex

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

network:
  session_affinity: true

env_variables:
  FLASK_ENV: "production"

entrypoint: gunicorn -b :$PORT app:app
