version: '3.8'

services:
  ted-extractor:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/clips:/app/static/clips
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 